[repository]
name = "hycov"
authors = ["DreamMaoMao", "DRAGONTOS"]
commit_pins = [
]

[hycov]
description = "hyprland overview mode"
authors = ["DreamMaoMao", "DRAGONTOS"]
output = "build/libhycov.so"
build = [
	"cmake -DCMAKE_BUILD_TYPE=Release -B build",
	"cmake --build build -j $(nproc)"
]
